.TH "DL-DISTRO" "1" "January 3, 2024" "dl-distro v2.0.0" "dl-distro Manual"
.nh
.ad l
.SH NAME
dl-distro - Bash script for downloading and verifying OS images.

.SH SYNOPSIS
\fIdl-distro\fR

\fIdl-distro\fR [OPTIONS]

\fIdl-distro\fR -d <DISTRO|JSON_QUERY> [OPTIONS]

.SH DESCRIPTION
dl-distro aims to make downloading and verifying OS images quick and easy.

It uses \fBjq\fR for data retrieval, \fBwget\fR for downloading, \fBgpg\fR for
signature verification, and validates checksums with the relevant algorithm.

.SH OPTIONS
.TP
.B -a
.RS
Toggle on or off automatic updating of the local JSON file.
.RE

.TP
.B -c
.RS
Generate a config file with default values.
.RE

.TP
.B -d <DISTRO|JSON_QUERY>
.RS
Specify distribution by its short name or a JSON query.
.RE

.TP
.B -D <KEY_ID>
.RS
Delete a stored GPG key using its GPG key id.
.RE

.TP
.B -h
.RS
Display help message containing options and distributions available.
.RE

.TP
.B -i <KEY_FILE>
.RS
Import a GPG key from a key file.
.RE

.TP
.B -l
.RS
List the stored GPG keys.
.RE

.TP
.B -n
.RS
Skip GPG, Minisign, or Signify key fetching and verification.
.RE

.TP
.B -p <PATH>
.RS
Download image to specified directory.
.RE

.TP
.B -P
.RS
Purge ALL the stored data. Includes GPG, Minisign, Signify keys and the JSON
file.
.RE

.TP
.B -s
.RS
Check if the URLs for the chosen image return a 200 status, indicating they are
valid URLs.
.RE

.TP
.B -u
.RS
Update the locally stored JSON file.
.RE

.TP
.B -V
.RS
Print dl-distro's current version.
.RE

.SH DISTRIBUTIONS
.TS
tab(|);
l l l.
\fBalma\fR | AlmaLinux OS | https://almalinux.org
\fBalpine\fR | Alpine Linux | https://alpinelinux.org
\fBarch\fR | Arch Linux | https://archlinux.org
\fBdebian\fR | Debian | https://debian.org
\fBfedora\fR | Fedora Linux | https://fedoraproject.org
\fBgparted\fR | GParted Live | https://gparted.org
\fBkali\fR | Kali Linux | https://kali.org
\fBmint\fR | Linux Mint | https://linuxmint.com
\fBnixos\fR | NixOS | https://nixos.org
\fBopenbsd\fR | OpenBSD | https://openbsd.org
\fBopensuse\fR | openSUSE | https://opensuse.org
\fBparrot\fR | ParrotOS | https://parrotsec.org
\fBqubes\fR | Qubes OS | https://qubes-os.org
\fBrocky\fR | Rocky Linux | https://rockylinux.org
\fBslackware\fR | Slackware Linux | http://slackware.com
\fBsolus\fR | Solus | https://getsol.us
\fBtails\fR | Tails | https://tails.net
\fBubuntu\fR | Ubuntu | https://ubuntu.com
\fBvoid\fR | Void Linux | https://voidlinux.org
\fBwhonix\fR | Whonix | https://whonix.org
.TE

.SH EXAMPLES
.TP
dl-distro
Main menu with all distributions. Pick one and choose an image to download.

.TP
dl-distro -d arch
Provide a distribution name to skip the main menu. This will prompt you with
additional choice menus, if necessary.

.TP
dl-distro -d arch.latest
You can skip the menus and start a download directly if you provide a JSON
query. The names used in the JSON query correspond directly to those in the
menus.

.TP
dl-distro -d arch.latest -p ~/Downloads
Download and verify the latest Arch Linux image, saving to the ~/Downloads
directory.

.SH FILES
.TP
.B CONFIG DIRECTORY
The config directory is \fI$XDG_CONFIG_HOME/dl-distro\fR. If
\fB$XDG_CONFIG_HOME\fR is unset, the directory will be
\fI$HOME/.config/dl-distro\fR.

\fIdl-distro.conf\fR is used to store dl-distro's config. Below are the
variables you can set. Values shown are default values used in the script,
please use quotes:

.RS
.TP
\fB    default_download_dir\fR="$PWD"
By default, dl-distro will use the \fB$PWD\fR variable if no download path is
provided with \fB-p\fR. To always download to a specific path, change this variable.
.TP
\fB    auto_update_enabled\fR="false"
Changing to \fBtrue\fR will download the JSON file from the master branch before
each run, ensuring always up-to-date data.
.TP
\fB    verification_enabled\fR="true"
Changing to \fBfalse\fR is like using \fB-n\fR always.
.TP
\fB    spider_mode_enabled\fR="false"
Changing to \fBtrue\fR is like using \fB-s\fR always.
.TP
\fB    gpg_keyserver\fR="hkps://keyserver.ubuntu.com"
Change the keyserver used to fetch GPG keys during runtime.
.RE

.RS
You can also override data in the JSON file by placing it in the config
directory. dl-distro will use this file over the one stored in the data
directory.
.RE

.TP
.B DATA DIRECTORY
The data directory is \fI$XDG_DATA_HOME/dl-distro\fR. If
\fB$XDG_DATA_HOME\fR is unset, the directory will be
\fI$HOME/.local/share/dl-distro\fR.

This directory is used to store the GPG keys, Minisign keys, Signify keys and
the JSON file. dl-distro relies on there being a locally stored JSON file.
Use the \fB-a\fR option to toggle on and off automatic updating of the file.
The \fB-u\fR option will force update the file.

.SH BUGS
Please report bugs on Codeberg https://codeberg.org/bashuser30/dl-distro/issues.

.SH AUTHORS
bashuser30 <bashuser30@mailbox.org>
